# language: generic

sudo: required
services: 
  - docker

before_install:
  - docker build -t haikal/react-test -f Dockerfile.dev ./client

script:
  - docker run -e CI=true haikal/react-test npm run test

after_success:
  - docker build -t haikal/multi-client ./client
  - docker build -t haikal/multi-nginx ./nginx
  - docker build -t haikal/multi-server ./server
  - docker build -t haikal/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push haikal/multi-client
  - docker push haikal/multi-nginx
  - docker push haikal/multi-server
  - docker push haikal/multi-worker